### ISSUE TITLE
data/Animals.csv file not found

### ISSUE THREAD

**Issue by slashdottir** [stared/thinking-in-tensors-writing-in-pytorch#9]
when running on colab

https://colab.research.google.com/github/stared/thinking-in-tensors-writing-in-pytorch/blob/master/3%20Linear%20regression.ipynb#scrollTo=s5gdu-mRRiwo

![image](https://user-images.githubusercontent.com/47145634/66716760-6b1d6580-ed86-11e9-94b6-a73cc4d8c477.png)

**Comment by stared** [comment]
@jlj0n3s Right now the workaround is to manually upload the files from https://github.com/stared/thinking-in-tensors-writing-in-pytorch/tree/master/data.

I will look into other options (e.g. hard-coding the path).

**Comment by stared** [comment]
Solved!
